name: "Neon Branching Action"
description: "Handle creating and deleting databes branches on Neon.tech"
inputs:
  api_key: # id of input
    description: "neon.tech api key"
    required: true
  project_id: # id of input
    description: "neon.tech project id"
    required: true
  branch_name: # id of input
    description: "name for the new branch"
    required: true
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node16"
  main: "dist/index.js"
